// data.js
const variableNamesWithTypes = {
    anglais: {
        age: "integer",
        name: "string",
        userScore: "integer",
        count: "integer",
        total: "float",
        sum: "float",
        product: "float",
        average: "float",
        max: "float",
        min: "float",
        height: "float",
        width: "float",
        length: "float",
        size: "integer",
        position: "integer",
        status: "string",
        color: "string",
        date: "string",
        flag: "boolean",
        isActive: "boolean",
        hasItems: "boolean",
        isVisible: "boolean",
        // Ajout de noms de variables moins explicites
        x: "float",
        y: "float",
        z: "float",
        i: "integer",
        j: "integer",
        k: "integer",
        // Noms conformes à PEP8
        itemCount: "integer",
        dataPoints: "float",
        isComplete: "boolean",
        isValid: "boolean",
        canProceed: "boolean"
    },
    français: {
        age: "integer",
        nom: "string",
        scoreUtilisateur: "integer",
        compteur: "integer",
        total: "float",
        somme: "float",
        produit: "float",
        moyenne: "float",
        maximum: "float",
        minimum: "float",
        hauteur: "float",
        largeur: "float",
        longueur: "float",
        taille: "integer",
        position: "integer",
        statut: "string",
        couleur: "string",
        date: "string",
        drapeau: "boolean",
        estActif: "boolean",
        aDesObjets: "boolean",
        estVisible: "boolean",
        // Ajout de noms de variables moins explicites
        x: "float",
        y: "float",
        z: "float",
        i: "integer",
        j: "integer",
        k: "integer",
        // Noms conformes à PEP8
        nombreArticles: "integer",
        pointsDonnees: "float",
        estComplet: "boolean",
        estValide: "boolean",
        peutContinuer: "boolean"
    }
};
